name: Build Detection Vetements

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install OpenCV
      run: |
        Write-Host "Téléchargement d'OpenCV..."
        $url = "https://github.com/opencv/opencv/releases/download/4.8.0/opencv-4.8.0-windows.exe"
        $output = "opencv-installer.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        
        Write-Host "Extraction d'OpenCV..."
        Start-Process -FilePath $output -ArgumentList "-o", ".", "-y" -Wait -NoNewWindow
        Remove-Item $output
        
        Write-Host "OpenCV installé avec succès!"
        
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.24.0'
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64 -DOpenCV_DIR=../opencv/build/x64/vc16/lib/cmake/opencv4
        
    - name: Build application
      run: |
        cd build
        cmake --build . --config Release
        
    - name: Create portable package
      run: |
        Write-Host "Création du package portable..."
        mkdir DetectionVetements_Portable
        
        # Copier l'exécutable principal
        Copy-Item "build\Release\detection_vetements.exe" "DetectionVetements_Portable\"
        
        # Copier les DLLs OpenCV
        Copy-Item "opencv\build\x64\vc16\bin\*.dll" "DetectionVetements_Portable\"
        
        # Copier les DLLs Visual C++ Runtime
        Copy-Item "C:\Windows\System32\msvcp140.dll" "DetectionVetements_Portable\" -ErrorAction SilentlyContinue
        Copy-Item "C:\Windows\System32\vcruntime140.dll" "DetectionVetements_Portable\" -ErrorAction SilentlyContinue
        
        Write-Host "Package portable créé avec succès!"
        
    - name: Create README for portable version
      run: |
        $content = "# Detection de Vetements - Version Portable`n`n## Utilisation:`n1. Double-cliquez sur detection_vetements.exe`n2. L'application s'ouvrira automatiquement`n`n## Controles:`n- Q: Quitter`n- S: Sauvegarder une image`n- R: Redemarrer la detection`n`n## Note:`nCette version est 100%% portable - aucune installation requise!`n`n## Compatibilite:`n- Windows 10/11 (64-bit)`n- Aucune installation requise`n- Fonctionne sur clé USB`n`nVersion: 1.0.0`nDate: $(Get-Date -Format 'yyyy-MM-dd')"
        $content | Out-File -FilePath "DetectionVetements_Portable\README.txt" -Encoding UTF8
        
    - name: Create launcher script
      run: |
        $launcher = "@echo off`necho ========================================`necho Detection de Vetements - Version Portable`necho ========================================`necho.`necho Lancement de l'application...`necho.`ndetection_vetements.exe`nif %errorlevel% neq 0 (`necho.`necho ERREUR: Impossible de lancer l'application`necho Verifiez que votre webcam est connectee`necho.`npause`n)"
        $launcher | Out-File -FilePath "DetectionVetements_Portable\Lancer_Application.bat" -Encoding ASCII
        
    - name: List package contents
      run: |
        Write-Host "Contenu du package portable:"
        Get-ChildItem "DetectionVetements_Portable" | Format-Table Name, Length
        
    - name: Upload portable package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: DetectionVetements_Portable
        path: DetectionVetements_Portable/
        retention-days: 30
        
    - name: Create release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: DetectionVetements_Portable/*
        tag_name: v1.0.0
        name: Version Portable 1.0.0
        body: |
          # Detection de Vetements - Version Portable
          
          Application C++ portable pour detecter automatiquement les vetements via webcam.
          
          ## Installation
          Aucune installation requise! Juste extraire et lancer detection_vetements.exe
          
          ## Fonctionnalites
          - Detection en temps reel via webcam
          - Classification automatique (t-shirt, pull, chemise, etc.)
          - Interface graphique intuitive
          - Sauvegarde d'images
          - 100% portable
          
          ## Utilisation
          1. Double-cliquez sur detection_vetements.exe
          2. L'application s'ouvre automatiquement
          3. Utilisez Q pour quitter, S pour sauvegarder
          
          ## Compatibilite
          - Windows 10/11 (64-bit)
          - Aucune installation requise
          - Fonctionne sur clé USB
          
          ## Contenu du package
          - detection_vetements.exe (application principale)
          - DLLs OpenCV (bibliothèques de vision)
          - DLLs Visual C++ Runtime
          - Lancer_Application.bat (script de lancement)
          - README.txt (instructions d'utilisation)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 